device:

  characteristics:
    name: n45_d13
    charge_carrier: h
    operation_mode: acc

  constraints:
    abs_max_current: 1.5e-9
    abs_max_gate_differential: 2
    abs_max_gate_voltage: 2.5

  gates:
    LB:
      label: Left Barrier Gate
      type: barrier
      channel: 3
      step: 0.01
      unit: V
    RB:
      label: Right Barrier Gate
      type: barrier
      channel: 5
      step: 0.01
      unit: V
    L:
      label: Lead Barrier Gate
      type: lead
      channel: 6
      step: 0.01
      unit: V
    S:
      label: Source Ohmic Gate
      type: ohmic
      channel: 3
      step: 0.01
      unit: V
    P:
      label: Plunger Gate
      type: plunger
      channel: 4
      step: 0.01
      unit: V

setup:
  voltage_source: ivvi
  multimeter: agilent
  preamp_bias: 0.0
  preamp_sensitivity: 1.0e-8
  voltage_divider: 1.0e-3
  voltage_resolution: 1.0e-3


