device:

  characteristics:
    name: Tunnel_Falls_3D1S_3
    charge_carrier: e
    operation_mode: acc

  constraints:
    abs_max_current: 12e-9
    abs_max_gate_differential: 2.0
    abs_max_gate_voltage: 1.7

  gates:
    
    CG0b:
      label: Screening Gate
      type: screening
      channel: 2
      step: 0.01
      unit: V
    F1:
      label: Accumulation Gate
      type: accumulation
      channel: 3
      step: 0.01 
      unit: V
    S3:
      label: Source Ohmic Gate
      type: ohmic
      channel: 4
      step: 0.01
      unit: V
    AC3:
      label: Accumulation Gate
      type: accumulation
      channel: 5
      step: 0.01
      unit: V
    AC2:
      label: Accumulation Gate
      type: accumulation
      channel: 6
      step: 0.01
      unit: V   
    B20:
      label: Barrier Gate
      type: barrier
      channel: 7
      step: 0.01
      unit: V 
    B21:
      label: Barrier Gate
      type: barrier
      channel: 8
      step: 0.01
      unit: V 
    P20: 
      label: Plunger Gate
      type: plunger
      channel: 1
      step: 0.01
      unit: V 

setup:
  voltage_sources:
    voltage_source_1: ivvi
    voltage_source_2: SIM928
  multimeter: agilent
  preamp_bias: 0.0
  preamp_sensitivity: 1.0e-7
  voltage_divider: 1.0e-2
  voltage_resolution: 1.0e-3


