# the dummy_station.yaml file initializes an overly complicated station to test the gui
instruments:
  DummyInst:
    type: gui.RandomDummy #qcodes.instrument_drivers.mock_instruments.DummyInstrument
  DummyInst4:
    type: gui.RandomDummy #qcodes.instrument_drivers.mock_instruments.DummyInstrument

    