instruments:
  DummyInst:
    type: gui.RandomDummy #qcodes.instrument_drivers.mock_instruments.DummyInstrument
  DummyInst2:
    type: gui.RandomDummy #qcodes.instrument_drivers.mock_instruments.DummyInstrument