device:

  characteristics:
    name: 3D1S_w151_1
    charge_carrier: e
    operation_mode: acc

  constraints:
    abs_max_current_triple_dot: 20e-9
    abs_max_current_SET_dot: 10e-9
    abs_max_gate_differential: 1.5
    abs_max_gate_voltage: 1.5
    abs_max_ohmic_bias: 1e-3

  gates:
    S0:
      label: Left Dot Ohmic
      type: Dot Ohmic
      channel: module1.dac10
    S3:
      label: Right Sensor Ohmic
      type: Sensor Ohmic
      channel: module1.dac5
    SG1:
      label: Horizontal Screening Gate
      type: Central Screening
      channel: module2.dac8
    CG0a:
      label: Dot Screening Gate
      type:  Dot Screening
      channel: module2.dac7
    CG0b:
      label: Sensor Screening Gate
      type: Sensor Screening
      channel: module1.dac4
    AC0:
      label: Left Dot Accumulation Gate
      type:  Dot Accumulation
      channel: module2.dac5
    AC1:
      label: Right Dot Accumulation Gate
      type:  Dot Accumulation
      channel: module1.dac2
    AC2:
      label: Right Sensor Accumulation Gate
      type:  Sensor Accumulation
      channel: module1.dac3
    F1 + AC3:
      label: Left Sensor Accumulation Gate and Flanking Gates
      type: Sensor Accumulation
      channel: module2.dac4
    B0:
      label: Left Barrier Gate
      type: Dot Barrier
      channel: module2.dac10
    B1:
      label: Dot 1-2 Barrier Gate
      type: Dot Barrier
      channel: module2.dac6
    B2:
      label: Dot 2-3 Barrier Gate
      type: Dot Barrier
      channel: module1.dac6
    B3:
      label: Right Barrier Gate
      type: Dot Barrier
      channel: module2.dac11
    B20:
      label: Left Sensor Barrier Gate
      type: Sensor Barrier
      channel: module1.dac9
    B21:
      label: Right Sensor Barrier Gate
      type: Sensor Barrier
      channel: module1.dac8
    P0:
      label: Left Dot Plunger
      type: Dot Plunger
      channel: module2.dac2
    P1:
      label: Middle Dot Plunger
      type: Dot Plunger
      channel: module2.dac1
    P2:
      label: Right Dot Plunger
      type: Dot Plunger
      channel: module1.dac1
    P20:
      label: Sensor Plunger
      type: Sensor Plunger
      channel: module2.dac3
setup:
  triple_dot_preamp:
    preamp_bias: 0.0
    preamp_sensitivity: 1.0e-8
  SET_dot_preamp:
    preamp_bias: 0.0
    preamp_sensitivity: 1.0e-8
  voltage_dividers:
    voltage_divider_triple_dot: 1.0e-3
    voltage_divider_SET_dot: 1.0e-3

