device:

  characteristics:
    name: 3D1S_w151_1
    charge_carrier: e
    operation_mode: acc

  constraints:
    abs_max_current_triple_dot: 20e-9
    abs_max_current_SET_dot: 10e-9
    abs_max_gate_differential: 1.5
    abs_max_gate_voltage: 1.5
    abs_max_ohmic_bias: 1e-3

  gates:
    S0:
      label: Left Dot Ohmic
      type: Dot Ohmic
      channel: module2.dac16
    SG1:
      label: Horizontal Screening Gate
      type: Central Screening
      channel: module2.dac15
    AC0:
      label: Left Accumulation Gate 
      type: Dot Accumulation
      channel: module2.dac14
    B0:
      label: Left Dot Barrier Gate
      type:  Dot Barrier
      channel: module2.dac13