instruments:
  spi_rack:
    type: qblox_instruments.qcodes_drivers.spi_rack.SpiRack
    address: COM3
    initializer: spi rack

    modules:
      module1:
        slot: 8
        type: D5a

      module2:
        slot: 7
        type: D5a

  agilent_left:
    type: qcodes.instrument_drivers.agilent.Agilent_34410A.Agilent34410A
    address: TCPIP0::169.254.10.10::inst0::INSTR
    initializer: agilent

    NPLC: 1.0
    autorange: on

  agilent_right:
    type: qcodes.instrument_drivers.agilent.Agilent_34410A.Agilent34410A
    address: TCPIP0::169.254.4.10::inst0::INSTR
    initializer: agilent

    NPLC: 1.0
    autorange: on
