# MODEL TRAINING DEVICE

device:

  cuda:

    num_workers: 4

  cpu:

    num_workers: 0

# MODEL 1

dot_num:

  info:
  
    class_dict: {"ND": 0, "LD": 1, "CD": 2, "RD": 3, "DD": 4}
    num_of_classes: 5
    data_key: 'state'
    files_to_ignore: ["^2017.*", "exp_large_(07|08|09|10|11|12)", "d_.*"] # checks if string in file name
    custom_annotations_file: "dot_num_custom.json"

  hyperparameters:

    learning_rate: 2.0e-4
    augments_per_sim_img: 2
    augments_per_exp_img: 50
    num_epochs: 7000
    batch_num: 10
    dataset_size: 1001
    train_val_split: 0.8
    batch_size_per_img: 128

# MODEL 2

charge_state:

  info:
    
    # numbers come from charge state -> unique number function in annotate_data.py
    class_dict: {"(0,0)": 0, "(0,1)": 5, "(0,2)": 10, "(1,0)": 3, "(1,1)": 8, "(1,2)": 13, "(2,0)": 6, "(2,1)": 11, "(2,2)": 16}
    num_of_classes: 9
    data_key: 'charge'
    files_to_ignore: ["^2020.*", "exp_large_(07|08|09|10|11|12)", "d_.*"] # checks if string in file name
    custom_annotations_file: "charge_state_custom.json"

  hyperparameters:

    learning_rate: 2.5e-4
    augments_per_sim_img: 2
    augments_per_exp_img: 50
    num_epochs: 1
    batch_num: 1
    dataset_size: 1001
    train_val_split: 0.8
    batch_size_per_img: 128
